package com.intranet.service.FinanceReportEmail;

import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

@Service
public class FinancialPdfTemplateBuilder {

    /**
     * Build a safe, well-formed XHTML string for the financial report.
     * Java 8 compatible (no text blocks). Escapes XML entities to avoid SAX errors.
     *
     * @param data      Map response from TimesheetFinanceReportService
     * @param monthName Month name (e.g. "November")
     * @param year      Year (e.g. 2025)
     * @return XHTML string
     */
    // @SuppressWarnings("unchecked")
    public String buildFinanceHtml(Map<String, Object> data, String monthName, int year) {

        if (data == null) data = java.util.Collections.emptyMap();

        StringBuilder html = new StringBuilder(48_000);

        // Header / styles (kept simple and inline-safe)
        html.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
        html.append("<!DOCTYPE html>");
        html.append("<html xmlns='http://www.w3.org/1999/xhtml'>");
        html.append("<head>");
        html.append("<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'/>");
        html.append("<style type='text/css'>");
        html.append("body { font-family: Arial, Helvetica, sans-serif; margin: 20px; color:#222; }");
        html.append("h1 { color:#1F4E79; font-size:20px; margin:0 0 8px 0; }");
        html.append("h2 { margin-top:18px; color:#2C3E50; font-size:14px; }");
        html.append("table { width:100%; border-collapse:collapse; margin-top:8px; }");
        html.append("th, td { border:1px solid #d0d7de; padding:6px; font-size:12px; vertical-align:top; }");
        html.append("th { background:#f0f3f7; text-align:left; }");
        html.append(".section { margin-top:16px; }");
        html.append(".muted { color:#666; font-size:12px; }");
        html.append(".group-header { margin-top:12px; font-weight:600; }");
        html.append(".small { font-size:11px; }");
        // remove forced page-break styles so content flows in one long PDF
        html.append("</style>");
        html.append("</head>");
        html.append("<body>");

        // Title
        html.append("<h1>").append(escapeXml("Financial Report \u2014 " + safeToString(monthName) + " " + year)).append("</h1>");

        // ========== SUMMARY ==========
        html.append("<div class='section'>");
        html.append("<h2>").append(escapeXml("Summary")).append("</h2>");
        html.append("<table>");
        appendRow(html, "Total Employees", data.get("totalEmployees"));
        appendRow(html, "Total Working Days", data.get("totalWorkingDays"));
        appendRow(html, "Total Holiday Dates", data.get("totalHolidayDates"));
        appendRow(html, "Total Hours Worked", data.get("totalHoursWorked"));
        appendRow(html, "Total Billable Hours", data.get("totalBillableHours"));
        appendRow(html, "Total Non-Billable Hours", data.get("totalNonBillableHours"));
        appendRow(html, "Auto-Generated Hours", data.get("autoGeneratedHours"));
        appendRow(html, "Utilization Rate", data.get("utilizationRate"));
        html.append("</table>");
        html.append("</div>");

        // ========== HOURS BREAKDOWN ==========
        Object hbObj = data.get("hoursBreakdown");
        if (hbObj instanceof Map) {
            Map<String, Object> hours = (Map<String, Object>) hbObj;
            html.append("<div class='section'>");
            html.append("<h2>").append(escapeXml("Hours Breakdown")).append("</h2>");
            html.append("<table>");
            for (Map.Entry<String, Object> e : hours.entrySet()) {
                appendRow(html, prettifyLabel(e.getKey()), e.getValue());
            }
            html.append("</table>");
            html.append("</div>");
        }

        // ========== EMPLOYEE BREAKDOWN ==========
        Object empObj = data.get("employeeBreakdown");
        if (empObj instanceof List) {
            List<Map<String, Object>> emp = (List<Map<String, Object>>) empObj;
            html.append("<div class='section'>");
            html.append("<h2>").append(escapeXml("Employee Breakdown")).append("</h2>");

            html.append("<table>");
            html.append("<tr>");
            html.append("<th>").append(escapeXml("Name")).append("</th>");
            html.append("<th>").append(escapeXml("Working Days")).append("</th>");
            html.append("<th>").append(escapeXml("Billable")).append("</th>");
            html.append("<th>").append(escapeXml("Non-Billable")).append("</th>");
            html.append("<th>").append(escapeXml("Auto")).append("</th>");
            html.append("<th>").append(escapeXml("Total")).append("</th>");
            html.append("<th>").append(escapeXml("Productivity")).append("</th>");
            html.append("</tr>");

            for (Map<String, Object> e : emp) {
                html.append("<tr>");
                html.append(td(e.get("name")));
                html.append(td(e.get("workingDays")));
                html.append(td(e.get("billableHours")));
                html.append(td(e.get("nonBillableHours")));
                html.append(td(e.get("autoGeneratedHours")));
                html.append(td(e.get("totalHours")));
                html.append(td(e.get("productivity")));
                html.append("</tr>");
            }

            html.append("</table>");
            html.append("</div>");
        }

        // ========== PROJECT BREAKDOWN ==========
        Object projObj = data.get("projectBreakdown");
        if (projObj instanceof List) {
            List<Map<String, Object>> projects = (List<Map<String, Object>>) projObj;
            html.append("<div class='section'>");
            html.append("<h2>").append(escapeXml("Project Breakdown")).append("</h2>");

            html.append("<table>");
            html.append("<tr>");
            html.append("<th>").append(escapeXml("Project")).append("</th>");
            html.append("<th>").append(escapeXml("Total Hrs")).append("</th>");
            html.append("<th>").append(escapeXml("Billable")).append("</th>");
            html.append("<th>").append(escapeXml("Non-Billable")).append("</th>");
            html.append("<th>").append(escapeXml("Team Members")).append("</th>");
            html.append("</tr>");

            for (Map<String, Object> p : projects) {
                html.append("<tr>");
                html.append(td(p.get("projectName")));
                html.append(td(p.get("totalHours")));
                html.append(td(p.get("billableHours")));
                html.append(td(p.get("nonBillableHours")));
                html.append(td(p.get("teamMembers")));
                html.append("</tr>");
            }

            html.append("</table>");
            html.append("</div>");
        }

        // ========== PROJECT -> MEMBERS (GROUPED TABLES) ==========
        Object groupedObj = data.get("projectUserHoursBreakdown");
        if (groupedObj instanceof List) {
            List<Map<String, Object>> grouped = (List<Map<String, Object>>) groupedObj;
            html.append("<div class='section'>");
            html.append("<h2>").append(escapeXml("Project Members Breakdown")).append("</h2>");

            for (Map<String, Object> proj : grouped) {
                html.append("<div class='group-header'>")
                    .append(escapeXml("Project: " + safeToString(proj.get("projectName"))))
                    .append("</div>");

                // grouped table header
                html.append("<table>");
                html.append("<tr>");
                html.append("<th>").append(escapeXml("Member")).append("</th>");
                html.append("<th>").append(escapeXml("Billable")).append("</th>");
                html.append("<th>").append(escapeXml("Non-Billable")).append("</th>");
                html.append("<th>").append(escapeXml("Total")).append("</th>");
                html.append("<th>").append(escapeXml("Contribution")).append("</th>");
                html.append("</tr>");

                Object membersObj = proj.get("members");
                if (membersObj instanceof List) {
                    List<Map<String, Object>> members = (List<Map<String, Object>>) membersObj;
                    for (Map<String, Object> m : members) {
                        html.append("<tr>");
                        html.append(td(m.get("memberName")));
                        html.append(td(m.get("billableHours")));
                        html.append(td(m.get("nonBillableHours")));
                        html.append(td(m.get("totalHours")));
                        html.append(td(m.get("contribution")));
                        html.append("</tr>");
                    }
                } else {
                    html.append("<tr><td colspan='5' class='muted'>No members</td></tr>");
                }

                html.append("</table>");
            }

            html.append("</div>");
        }

        // ========== LEAVE BREAKDOWN ==========
        Object leaveObj = data.get("leaveHoursBreakdown");
        if (leaveObj instanceof List) {
            List<Map<String, Object>> leaves = (List<Map<String, Object>>) leaveObj;
            html.append("<div class='section'>");
            html.append("<h2>").append(escapeXml("Leave Hours Breakdown")).append("</h2>");

            html.append("<table>");
            html.append("<tr>");
            html.append("<th>").append(escapeXml("Employee")).append("</th>");
            html.append("<th>").append(escapeXml("No. of Days")).append("</th>");
            html.append("<th>").append(escapeXml("Hours")).append("</th>");
            html.append("<th>").append(escapeXml("Contribution")).append("</th>");
            html.append("</tr>");

            for (Map<String, Object> l : leaves) {
                html.append("<tr>");
                html.append(td(l.get("userName")));
                html.append(td(l.get("noOfDays")));
                html.append(td(l.get("leaveHours")));
                html.append(td(l.get("contribution")));
                html.append("</tr>");
            }

            html.append("</table>");
            html.append("</div>");
        }

        html.append("<div class='section'>");
        html.append("<h2>Report Notes</h2>");
        html.append("<ul style='font-size:12px; line-height:1.6; padding-left:18px;'>");
        html.append("<li><strong>Billable Hours</strong> = Total hours spent on tasks classified as billable across all projects.</li>");
        html.append("<li><strong>Standard Holiday Hours</strong> = Calculated as 8 hours per holiday falling on Monday–Friday.</li>");
        html.append("<li><strong>Non-Billable Hours</strong> = Sum of all task hours marked as non-billable across all projects + Standard holiday hours.</li>");
        html.append("<li><strong>Total Hours</strong> = Billable Hours + Non-Billable Hours.</li>");
        html.append("<li><strong>Billable Utilization %</strong> = Billable Hours ÷ Total Hours × 100.</li>");
        html.append("<li><strong>Minimum Monthly Hours</strong> = 176 hours.</li>");
        html.append("<li><strong>Productivity %</strong> = (Total Hours − Holiday Hours) ÷ Minimum Monthly Hours × 100.</li>");
        html.append("<li><strong>Employee Leave Hours Contribution</strong> = (leaveHours ÷ totalLeaveHours) × 100.</li>");
        html.append("<li><strong>Employee Project Hours Contribution</strong> = (totalHours ÷ totalProjectHours) × 100.</li>");
        html.append("</ul>");
        html.append("</div>");


        // Generated on
        html.append("<p class='muted' style='text-align:center;margin-top:14px;'>");
        html.append(escapeXml("Report Generated by TimeSheet Management System on " + LocalDateTime.now().toString()));
        html.append("</p>");

        html.append("</body></html>");

        return html.toString();
    }

    // ===== Helpers =====

    private void appendRow(StringBuilder sb, String label, Object value) {
        sb.append("<tr><th>").append(escapeXml(prettifyLabel(label))).append("</th><td>")
          .append(escapeXml(safeToString(value)))
          .append("</td></tr>");
    }

    private String td(Object v) {
        return "<td>" + escapeXml(safeToString(v)) + "</td>";
    }

    private String safeToString(Object o) {
        if (o == null) return "";
        return o.toString();
    }

    private String escapeXml(String s) {
        if (s == null) return "";
        StringBuilder out = new StringBuilder(s.length() + 16);
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            switch (c) {
                case '&': out.append("&amp;"); break;
                case '<': out.append("&lt;"); break;
                case '>': out.append("&gt;"); break;
                case '"': out.append("&quot;"); break;
                case '\'': out.append("&#39;"); break;
                // NB: Avoid named entities like &nbsp; because XML parser may reject them.
                // If you need a non-breaking space, use numeric reference:
                case '\u00A0': out.append("&#160;"); break;
                default: out.append(c);
            }
        }
        return out.toString();
    }

    private String prettifyLabel(String key) {
        if (key == null) return "";
        // convert camelCase / snake_case to Title Case (simple)
        String s = key.replaceAll("_", " ");
        s = s.replaceAll("([a-z])([A-Z])", "$1 $2");
        String[] parts = s.split("\\s+");
        StringBuilder out = new StringBuilder();
        for (String p : parts) {
            if (p.isEmpty()) continue;
            out.append(Character.toUpperCase(p.charAt(0)));
            if (p.length() > 1) out.append(p.substring(1).toLowerCase());
            out.append(' ');
        }
        return out.toString().trim();
    }
}
