package com.intranet.service.RMS;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.TreeSet;
import java.util.stream.Collectors;

import org.springframework.stereotype.Service;
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;

import com.intranet.dto.rms.RMSInternalTaskHoursDTO;
import com.intranet.dto.rms.RMSProjectHoursDetailDTO;
import com.intranet.dto.rms.RMSProjectHoursResourceDTO;
import com.intranet.dto.rms.RMSProjectHoursSummaryResponseDTO;
import com.intranet.entity.InternalProject;
import com.intranet.entity.TimeSheet;
import com.intranet.entity.TimeSheetEntry;
import com.intranet.repository.InternalProjectRepo;
import com.intranet.repository.TimeSheetRepo;
import com.intranet.util.cache.ProjectDirectoryService;
import com.intranet.util.cache.UserDirectoryService;

import jakarta.servlet.http.HttpServletRequest;
import lombok.RequiredArgsConstructor;

@Service
@RequiredArgsConstructor
public class RMSProjectHoursSummaryService {

    private static final List<String> PLANNED_HOURS_KEYS = List.of(
            "plannedHours", "estimatedHours", "allocatedHours", "plannedEffort", "projectHours", "hours");
    private static final List<String> START_DATE_KEYS = List.of("startDate", "projectStartDate", "plannedStartDate");
    private static final List<String> END_DATE_KEYS = List.of("endDate", "projectEndDate", "plannedEndDate");

    private final TimeSheetRepo timeSheetRepo;
    private final InternalProjectRepo internalProjectRepo;
    private final ProjectDirectoryService projectDirectoryService;
    private final UserDirectoryService userDirectoryService;

    public RMSProjectHoursSummaryResponseDTO getProjectHoursSummary() {
        String authHeader = getAuthorizationHeader();
        Map<Long, Map<String, Object>> projectDirectory = projectDirectoryService.fetchAllProjects(authHeader);
        Map<Long, Map<String, Object>> userDirectory = userDirectoryService.fetchAllUsers(authHeader);
        List<InternalProject> internalProjects = internalProjectRepo.findAll();
        List<TimeSheet> allSheets = timeSheetRepo.findAllNonDraftWithEntries();

        List<TimeSheetEntry> allEntries = allSheets.stream()
                .filter(Objects::nonNull)
                .filter(ts -> !Boolean.TRUE.equals(ts.getAutoGenerated()))
                .flatMap(ts -> Optional.ofNullable(ts.getEntries()).orElse(Collections.emptyList()).stream())
                .filter(Objects::nonNull)
                .filter(entry -> entry.getProjectId() != null)
                .collect(Collectors.toList());

        Map<Long, List<TimeSheetEntry>> entriesByProject = allEntries.stream()
                .collect(Collectors.groupingBy(TimeSheetEntry::getProjectId));

        Map<Long, List<InternalProject>> internalProjectsByProject = internalProjects.stream()
                .filter(ip -> ip.getProjectId() != null)
                .collect(Collectors.groupingBy(ip -> ip.getProjectId().longValue()));

        Set<Long> projectIds = new TreeSet<>();
        projectIds.addAll(entriesByProject.keySet());

        List<RMSProjectHoursDetailDTO> projects = projectIds.stream()
                .map(projectId -> buildProjectSummary(
                        projectId,
                        projectDirectory.get(projectId),
                        entriesByProject.getOrDefault(projectId, Collections.emptyList()),
                        internalProjectsByProject.getOrDefault(projectId, Collections.emptyList()),
                        userDirectory))
                .sorted(Comparator.comparing(
                        RMSProjectHoursDetailDTO::getProjectName,
                        Comparator.nullsLast(String.CASE_INSENSITIVE_ORDER)))
                .collect(Collectors.toList());

        RMSProjectHoursSummaryResponseDTO response = new RMSProjectHoursSummaryResponseDTO();
        response.setGeneratedOn(LocalDate.now());
        response.setTotalProjects(projects.size());
        response.setTotalPlannedHours(sum(projects.stream().map(RMSProjectHoursDetailDTO::getPlannedHours).toList()));
        response.setTotalBillableHours(sum(projects.stream().map(RMSProjectHoursDetailDTO::getBillableHours).toList()));
        response.setTotalNonBillableHours(sum(projects.stream().map(RMSProjectHoursDetailDTO::getNonBillableHours).toList()));
        response.setTotalActualHours(sum(projects.stream().map(RMSProjectHoursDetailDTO::getActualHours).toList()));
        response.setTotalPendingHours(sum(projects.stream().map(RMSProjectHoursDetailDTO::getPendingHours).toList()));
        response.setProjects(projects);

        return response;
    }

    private RMSProjectHoursDetailDTO buildProjectSummary(
            Long projectId,
            Map<String, Object> projectInfo,
            List<TimeSheetEntry> projectEntries,
            List<InternalProject> internalProjects,
            Map<Long, Map<String, Object>> userDirectory) {

        BigDecimal billableHours = sum(projectEntries.stream()
                .filter(TimeSheetEntry::isBillable)
                .map(TimeSheetEntry::getHoursWorked)
                .toList());

        BigDecimal nonBillableHours = sum(projectEntries.stream()
                .filter(entry -> !entry.isBillable())
                .map(TimeSheetEntry::getHoursWorked)
                .toList());

        BigDecimal actualHours = billableHours.add(nonBillableHours);
        LocalDate startDate = firstLocalDate(projectInfo, START_DATE_KEYS);
        LocalDate endDate = firstLocalDate(projectInfo, END_DATE_KEYS);
        BigDecimal plannedHours = resolvePlannedHours(projectInfo, projectEntries, startDate, endDate);
        BigDecimal pendingHours = plannedHours.compareTo(BigDecimal.ZERO) > 0
                ? plannedHours.subtract(actualHours).max(BigDecimal.ZERO)
                : BigDecimal.ZERO;
        BigDecimal utilizationPercentage = plannedHours.compareTo(BigDecimal.ZERO) > 0
                ? actualHours.multiply(BigDecimal.valueOf(100))
                        .divide(plannedHours, 2, RoundingMode.HALF_UP)
                : BigDecimal.ZERO;

        RMSProjectHoursDetailDTO dto = new RMSProjectHoursDetailDTO();
        dto.setProjectId(projectId);
        dto.setProjectName(resolveProjectName(projectInfo, internalProjects, projectId));
        dto.setProjectType(internalProjects.isEmpty() ? "EXTERNAL" : "INTERNAL");
        dto.setStartDate(startDate);
        dto.setEndDate(endDate);
        dto.setPlannedHours(plannedHours);
        dto.setBillableHours(billableHours);
        dto.setNonBillableHours(nonBillableHours);
        dto.setActualHours(actualHours);
        dto.setPendingHours(pendingHours);
        dto.setUtilizationPercentage(utilizationPercentage);
        dto.setInternalHours(internalProjects.isEmpty() ? BigDecimal.ZERO : actualHours);
        dto.setResources(buildResources(projectInfo, projectEntries, userDirectory));
        dto.setInternalTasks(buildInternalTasks(projectEntries, internalProjects, userDirectory));
        return dto;
    }

    private List<RMSProjectHoursResourceDTO> buildResources(
            Map<String, Object> projectInfo,
            List<TimeSheetEntry> projectEntries,
            Map<Long, Map<String, Object>> userDirectory) {

        Map<Long, List<TimeSheetEntry>> entriesByUser = projectEntries.stream()
                .filter(entry -> entry.getTimeSheet() != null && entry.getTimeSheet().getUserId() != null)
                .collect(Collectors.groupingBy(entry -> entry.getTimeSheet().getUserId()));

        Map<Long, Map<String, Object>> projectMembers = extractProjectMembers(projectInfo);
        List<RMSProjectHoursResourceDTO> resources = new ArrayList<>();

        for (Map.Entry<Long, List<TimeSheetEntry>> entry : entriesByUser.entrySet()) {
            Long userId = entry.getKey();
            List<TimeSheetEntry> userEntries = entry.getValue();

            BigDecimal billableHours = sum(userEntries.stream()
                    .filter(TimeSheetEntry::isBillable)
                    .map(TimeSheetEntry::getHoursWorked)
                    .toList());

            BigDecimal nonBillableHours = sum(userEntries.stream()
                    .filter(e -> !e.isBillable())
                    .map(TimeSheetEntry::getHoursWorked)
                    .toList());

            Map<String, Object> memberInfo = projectMembers.getOrDefault(userId, userDirectory.get(userId));

            RMSProjectHoursResourceDTO dto = new RMSProjectHoursResourceDTO();
            dto.setResourceId(userId);
            dto.setResourceName(extractString(memberInfo, "name", "Unknown Resource"));
            dto.setResourceEmail(extractString(memberInfo, "email", null));
            dto.setBillableHours(billableHours);
            dto.setNonBillableHours(nonBillableHours);
            dto.setActualHours(billableHours.add(nonBillableHours));
            resources.add(dto);
        }

        resources.sort(Comparator.comparing(
                RMSProjectHoursResourceDTO::getResourceName,
                Comparator.nullsLast(String.CASE_INSENSITIVE_ORDER)));

        return resources;
    }

    private List<RMSInternalTaskHoursDTO> buildInternalTasks(
            List<TimeSheetEntry> projectEntries,
            List<InternalProject> internalProjects,
            Map<Long, Map<String, Object>> userDirectory) {

        if (internalProjects.isEmpty()) {
            return Collections.emptyList();
        }

        Map<Long, String> taskNames = internalProjects.stream()
                .filter(ip -> ip.getTaskId() != null)
                .collect(Collectors.toMap(
                        ip -> ip.getTaskId().longValue(),
                        InternalProject::getTaskName,
                        (left, right) -> left,
                        LinkedHashMap::new));

        Map<Long, List<TimeSheetEntry>> entriesByTask = projectEntries.stream()
                .filter(entry -> entry.getTaskId() != null)
                .collect(Collectors.groupingBy(TimeSheetEntry::getTaskId));

        return entriesByTask.entrySet().stream()
                .map(entry -> {
                    Long taskId = entry.getKey();
                    List<TimeSheetEntry> taskEntries = entry.getValue();

                    BigDecimal billableHours = sum(taskEntries.stream()
                            .filter(TimeSheetEntry::isBillable)
                            .map(TimeSheetEntry::getHoursWorked)
                            .toList());

                    BigDecimal nonBillableHours = sum(taskEntries.stream()
                            .filter(e -> !e.isBillable())
                            .map(TimeSheetEntry::getHoursWorked)
                            .toList());

                    RMSInternalTaskHoursDTO dto = new RMSInternalTaskHoursDTO();
                    dto.setTaskId(taskId);
                    dto.setTaskName(taskNames.getOrDefault(taskId, "Unknown Internal Task"));
                    dto.setBillableHours(billableHours);
                    dto.setNonBillableHours(nonBillableHours);
                    dto.setActualHours(billableHours.add(nonBillableHours));
                    dto.setResources(buildResources(null, taskEntries, userDirectory));
                    return dto;
                })
                .sorted(Comparator.comparing(
                        RMSInternalTaskHoursDTO::getTaskName,
                        Comparator.nullsLast(String.CASE_INSENSITIVE_ORDER)))
                .collect(Collectors.toList());
    }

    private Map<Long, Map<String, Object>> extractProjectMembers(Map<String, Object> projectInfo) {
        if (projectInfo == null) {
            return Collections.emptyMap();
        }

        Object membersObject = projectInfo.get("members");
        if (!(membersObject instanceof Collection<?> members)) {
            return Collections.emptyMap();
        }

        Map<Long, Map<String, Object>> result = new LinkedHashMap<>();
        for (Object memberObject : members) {
            if (!(memberObject instanceof Map<?, ?> rawMember)) {
                continue;
            }

            Object idObject = rawMember.get("id");
            if (!(idObject instanceof Number number)) {
                continue;
            }

            Long userId = number.longValue();
            Map<String, Object> normalized = new LinkedHashMap<>();
            normalized.put("name", rawMember.get("name"));
            normalized.put("email", rawMember.get("email"));
            result.put(userId, normalized);
        }
        return result;
    }

    private String resolveProjectName(Map<String, Object> projectInfo, List<InternalProject> internalProjects, Long projectId) {
        if (projectInfo != null && projectInfo.get("name") != null) {
            return projectInfo.get("name").toString();
        }
        if (!internalProjects.isEmpty() && internalProjects.get(0).getProjectName() != null) {
            return internalProjects.get(0).getProjectName();
        }
        return "Project " + projectId;
    }

    private BigDecimal resolvePlannedHours(
            Map<String, Object> projectInfo,
            List<TimeSheetEntry> projectEntries,
            LocalDate startDate,
            LocalDate endDate) {

        BigDecimal explicitPlannedHours = firstBigDecimal(projectInfo, PLANNED_HOURS_KEYS);
        if (explicitPlannedHours.compareTo(BigDecimal.ZERO) > 0) {
            return explicitPlannedHours;
        }

        if (startDate == null || endDate == null || endDate.isBefore(startDate)) {
            return BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
        }

        long workingDays = countWeekdaysInclusive(startDate, endDate);
        if (workingDays <= 0) {
            return BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
        }

        int resourceCount = resolvePlannedResourceCount(projectInfo, projectEntries);
        BigDecimal derivedHours = BigDecimal.valueOf(workingDays)
                .multiply(BigDecimal.valueOf(8L))
                .multiply(BigDecimal.valueOf(resourceCount));

        return derivedHours.setScale(2, RoundingMode.HALF_UP);
    }

    private int resolvePlannedResourceCount(Map<String, Object> projectInfo, List<TimeSheetEntry> projectEntries) {
        int configuredMembers = extractProjectMembers(projectInfo).size();
        if (configuredMembers > 0) {
            return configuredMembers;
        }

        long actualResources = projectEntries.stream()
                .filter(entry -> entry.getTimeSheet() != null && entry.getTimeSheet().getUserId() != null)
                .map(entry -> entry.getTimeSheet().getUserId())
                .distinct()
                .count();

        return actualResources > 0 ? (int) actualResources : 1;
    }

    private long countWeekdaysInclusive(LocalDate startDate, LocalDate endDate) {
        long workingDays = 0L;
        LocalDate current = startDate;

        while (!current.isAfter(endDate)) {
            DayOfWeek day = current.getDayOfWeek();
            if (day != DayOfWeek.SATURDAY && day != DayOfWeek.SUNDAY) {
                workingDays++;
            }
            current = current.plusDays(1);
        }

        return workingDays;
    }

    private BigDecimal firstBigDecimal(Map<String, Object> source, List<String> keys) {
        if (source == null) {
            return BigDecimal.ZERO;
        }
        for (String key : keys) {
            BigDecimal value = toBigDecimal(source.get(key));
            if (value != null) {
                return value;
            }
        }
        return BigDecimal.ZERO;
    }

    private LocalDate firstLocalDate(Map<String, Object> source, List<String> keys) {
        if (source == null) {
            return null;
        }
        for (String key : keys) {
            LocalDate value = toLocalDate(source.get(key));
            if (value != null) {
                return value;
            }
        }
        return null;
    }

    private BigDecimal toBigDecimal(Object value) {
        if (value == null) {
            return null;
        }
        if (value instanceof BigDecimal decimal) {
            return decimal;
        }
        if (value instanceof Number number) {
            return BigDecimal.valueOf(number.doubleValue()).setScale(2, RoundingMode.HALF_UP);
        }
        try {
            return new BigDecimal(value.toString().trim()).setScale(2, RoundingMode.HALF_UP);
        } catch (NumberFormatException ex) {
            return null;
        }
    }

    private LocalDate toLocalDate(Object value) {
        if (value == null) {
            return null;
        }
        if (value instanceof LocalDate localDate) {
            return localDate;
        }

        String text = value.toString().trim();
        if (text.isEmpty()) {
            return null;
        }

        try {
            return LocalDate.parse(text);
        } catch (DateTimeParseException ignored) {
        }

        try {
            return OffsetDateTime.parse(text).toLocalDate();
        } catch (DateTimeParseException ignored) {
        }

        int timeSeparator = text.indexOf('T');
        if (timeSeparator > 0) {
            try {
                return LocalDate.parse(text.substring(0, timeSeparator));
            } catch (DateTimeParseException ignored) {
            }
        }

        return null;
    }

    private String extractString(Map<String, Object> source, String key, String defaultValue) {
        if (source == null || source.get(key) == null) {
            return defaultValue;
        }
        String value = source.get(key).toString().trim();
        return value.isEmpty() ? defaultValue : value;
    }

    private BigDecimal sum(List<BigDecimal> values) {
        return values.stream()
                .filter(Objects::nonNull)
                .reduce(BigDecimal.ZERO, BigDecimal::add)
                .setScale(2, RoundingMode.HALF_UP);
    }

    private String getAuthorizationHeader() {
        ServletRequestAttributes attrs = (ServletRequestAttributes) RequestContextHolder.getRequestAttributes();
        if (attrs == null) {
            return null;
        }

        HttpServletRequest request = attrs.getRequest();
        return request.getHeader("Authorization");
    }
}
