package com.intranet.service.report;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;

import com.intranet.entity.TimeSheet;
import com.intranet.entity.TimeSheetEntry;
import com.intranet.repository.TimeSheetRepo;
import com.intranet.service.HolidayExcludeUsersService;

import lombok.RequiredArgsConstructor;

@Service
@RequiredArgsConstructor
public class TimesheetFinanceReportService {
    
    private final TimeSheetRepo timeSheetRepo;
    private final HolidayExcludeUsersService holidayExcludeUsersService;

    public Map<String, Object> getTimesheetFinanceReport(int month, int year) {

        // ✅ Step 1: Get holiday dates for users to exclude
        List<LocalDate> holidayDates = holidayExcludeUsersService.getUserHolidayDates(month);

        // ✅ Step 2: Filter to only include holidays from this year
        holidayDates = holidayDates.stream()
                .filter(date -> date != null && date.getYear() == year)
                .toList();

        // ✅ Step 2: Define current month range
        LocalDate firstDay = LocalDate.of(year, month, 1);
        LocalDate lastDay = firstDay.withDayOfMonth(firstDay.lengthOfMonth());
        int totalDaysInMonth = firstDay.lengthOfMonth();

        // ✅ Calculate working days
        int totalWorkingDays = totalDaysInMonth - holidayDates.size();
        
        // ✅ Step 4: Fetch all timesheets for this month and year
        List<TimeSheet> allTimeSheets = timeSheetRepo.findByWorkDateBetween(firstDay, lastDay);

        // ✅ Step 5: Filter strictly by same year (safety check)
        List<TimeSheet> currentYearTimeSheets = allTimeSheets.stream()
                .filter(ts -> ts.getWorkDate() != null && ts.getWorkDate().getYear() == year)
                .toList();

         // ✅ Step 6: Calculate total hours (include auto-generated)
        BigDecimal totalHours = currentYearTimeSheets.stream()
                .map(TimeSheet::getHoursWorked)
                .filter(h -> h != null)
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        // ✅ Step 7: Total Billable Hours (exclude auto-generated)
        BigDecimal totalBillableHours = currentYearTimeSheets.stream()
                .filter(ts -> !ts.getAutoGenerated()) // exclude system-generated
                .flatMap(ts -> ts.getEntries().stream())
                .filter(TimeSheetEntry::isBillable)
                .map(TimeSheetEntry::getHoursWorked)
                .filter(h -> h != null)
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        // ✅ Step 8: Total Non-Billable Hours (include auto-generated + non-billable entries)
        BigDecimal nonBillableFromEntries = currentYearTimeSheets.stream()
                .flatMap(ts -> ts.getEntries().stream())
                .filter(e -> !e.isBillable())
                .map(TimeSheetEntry::getHoursWorked)
                .filter(h -> h != null)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        
        BigDecimal autoGeneratedHours = currentYearTimeSheets.stream()
                .filter(TimeSheet::getAutoGenerated)
                .map(TimeSheet::getHoursWorked)
                .filter(h -> h != null)
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        BigDecimal totalNonBillableHours = nonBillableFromEntries.add(autoGeneratedHours); 

        // ✅ Step 8: Calculate Utilization Rate = (Billable / Non-Billable) * 100
        BigDecimal utilizationRate = BigDecimal.ZERO;
        String utilizationRateStr = "0.00%";

        if (totalNonBillableHours.compareTo(BigDecimal.ZERO) > 0) {
            utilizationRate = totalBillableHours
                    .divide(totalHours, 4, RoundingMode.HALF_UP)
                    .multiply(BigDecimal.valueOf(100))
                    .setScale(2, RoundingMode.HALF_UP);

            utilizationRateStr = utilizationRate.toPlainString() + "%";
        }


        Map<String, Object> response = Map.of(
            "month", month,
            "year", year,
            "totalHolidayDates", holidayDates.size(),
            "totalWorkingDays", totalWorkingDays,
            "holidayDates",holidayDates,
            "totalHoursWorked", totalHours,
            "totalBillableHours", totalBillableHours,
            "totalNonBillableHours", totalNonBillableHours,
            "utilizationRate", utilizationRateStr
        );

        return response;
    }
    
}
