package com.intranet.service;

import com.intranet.dto.LeavesAndHolidaysDTO;
import com.intranet.dto.MonthlyUserReportDTO;
import com.intranet.dto.WeekSummaryDTO;
import com.intranet.dto.WeeklySummaryDTO;
import com.intranet.dto.lms.LeaveDTO;
import com.intranet.dto.lms.UserLeaveBreakdown;
import com.intranet.entity.TimeSheet;
import com.intranet.entity.TimeSheetEntry;
import com.intranet.repository.TimeSheetRepo;
import com.intranet.service.report.TimesheetFinanceReportService;
import com.intranet.util.cache.LeaveDirectoryService;
import com.intranet.util.cache.ProjectDirectoryService;
import com.intranet.util.cache.UserDirectoryService;

import jakarta.servlet.http.HttpServletRequest;
import lombok.RequiredArgsConstructor;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.stereotype.Service;
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.*;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class MonthlyUserReportService {

        @Value("${leave.daily.hours}")
        private int leaveHours;

    private final TimeSheetRepo timeSheetRepo;
    private final HolidayExcludeUsersService holidayService;

    private final UserDirectoryService userDirectoryService;
    private final ProjectDirectoryService projectDirectoryService;

    private final TimesheetFinanceReportService timesheetFinanceReportService;

    private final LeaveDirectoryService leaveDirectoryService;
    
    private final WeeklySummaryService weeklySummaryService;
    // private final UserRepository userRepository; // optional for employee name

        // ✅ Authorization header builder
    private HttpEntity<Void> buildEntityWithAuth() {
        ServletRequestAttributes attrs = (ServletRequestAttributes) RequestContextHolder.getRequestAttributes();
        if (attrs == null) {
            return (HttpEntity<Void>) HttpEntity.EMPTY;
        }

        HttpServletRequest request = attrs.getRequest();
        String authHeader = request.getHeader("Authorization");

        HttpHeaders headers = new HttpHeaders();
        if (authHeader != null && !authHeader.isBlank()) {
            headers.set("Authorization", authHeader);
        }

        return new HttpEntity<>(headers);
    }

    public MonthlyUserReportDTO getMonthlyUserReport(Long userId, int month, int year) {

        LocalDate date = LocalDate.of(year, month, 1);
        int totalDaysInMonth = date.lengthOfMonth();

        HttpEntity<Void> entity=buildEntityWithAuth();
        String authHeader = entity.getHeaders().getFirst("Authorization");

        Map<Long,Map<String,Object>> allUsers = userDirectoryService.fetchAllUsers(authHeader);

        Map<Long,Map<String,Object>> projectDirectory = projectDirectoryService.fetchAllProjects(authHeader);

        LocalDate startOfMonth = LocalDate.of(year, month, 1);
        LocalDate endOfMonth = startOfMonth.withDayOfMonth(startOfMonth.lengthOfMonth());

        // 1️⃣ Fetch timesheets for the month
        List<TimeSheet> timeSheets = timeSheetRepo
                .findByUserIdAndWorkDateBetween(userId, startOfMonth, endOfMonth);

        // 2️⃣ Flatten all entries
        List<TimeSheetEntry> allEntries = timeSheets.stream()
                .flatMap(ts -> ts.getEntries().stream())
                .collect(Collectors.toList());

        // 5. Day-wise summary: bucket entries by day-of-week, accumulating raw minutes
        // (using doubleValue() on HH.MM-formatted hoursWorked silently produces wrong totals).
        Map<String, Long> dayWiseMinutes = new HashMap<>();
        for (TimeSheetEntry e : allEntries) {
            if (e.getTimeSheet() == null || e.getTimeSheet().getWorkDate() == null) continue;
            if (e.getFromTime() == null || e.getToTime() == null) continue;
            String day = e.getTimeSheet().getWorkDate().getDayOfWeek().name().toLowerCase();
            long mins = java.time.Duration.between(e.getFromTime(), e.getToTime()).toMinutes();
            dayWiseMinutes.merge(day, mins, Long::sum);
        }
        // Auto-generated timesheets have no fromTime/toTime entries; trust their stored hoursWorked.
        for (TimeSheet ts : timeSheets) {
            if (!Boolean.TRUE.equals(ts.getAutoGenerated())) continue;
            String day = ts.getWorkDate().getDayOfWeek().name().toLowerCase();
            dayWiseMinutes.merge(day, com.intranet.service.TimeUtil.hhmmToMinutes(ts.getHoursWorked()), Long::sum);
        }

        List<String> orderedDays = Arrays.asList(
                "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"
        );

        // Emit as decimal hours for the chart (8h30m = 8.5). Uses raw minutes — no HH.MM corruption.
        Map<String, Double> dayWiseSummary = new LinkedHashMap<>();
        for (String day : orderedDays) {
            dayWiseSummary.put(day, dayWiseMinutes.getOrDefault(day, 0L) / 60.0);
        }


        // ✅ Step 7: Total Billable Hours (exclude auto-generated) — recomputed from raw fromTime/toTime
        List<TimeSheetEntry> nonAutoEntries = timeSheets.stream()
                .filter(ts -> !Boolean.TRUE.equals(ts.getAutoGenerated()))
                .flatMap(ts -> ts.getEntries().stream())
                .collect(Collectors.toList());

        BigDecimal totalBillableHours = com.intranet.service.TimeUtil.sumEntryHours(
                nonAutoEntries.stream().filter(TimeSheetEntry::isBillable).collect(Collectors.toList()));

        // ✅ Step 8: Non-Billable from entries + auto-generated timesheet hours
        BigDecimal nonBillableFromEntries = com.intranet.service.TimeUtil.sumEntryHours(
                timeSheets.stream()
                        .flatMap(ts -> ts.getEntries().stream())
                        .filter(e -> !e.isBillable())
                        .collect(Collectors.toList()));

        BigDecimal autoGeneratedHours = com.intranet.service.TimeUtil.sumHours(
                timeSheets.stream()
                        .filter(ts -> Boolean.TRUE.equals(ts.getAutoGenerated()))
                        .map(TimeSheet::getHoursWorked)
                        .collect(Collectors.toList()));

        BigDecimal totalNonBillableHours = com.intranet.service.TimeUtil.sumHours(
                java.util.List.of(nonBillableFromEntries, autoGeneratedHours));

        // 6️⃣ Unique active project count
        int activeProjectsCount = allEntries.stream()
                .map(TimeSheetEntry::getProjectId)
                .filter(Objects::nonNull)
                .collect(Collectors.toSet())
                .size();

        List<LocalDate> HolidayDates = holidayService.getUserHolidaysMonthYear(userId, month, year);
        int totalHolidays = HolidayDates.size();


        UserLeaveBreakdown totalLeavesData = calculateLeaveDetailsForUserReport(userId, month, year,authHeader);
        
        
        LeavesAndHolidaysDTO leavesAndHolidays = new LeavesAndHolidaysDTO();
        leavesAndHolidays.setTotalHolidays(totalHolidays);
        leavesAndHolidays.setHolidayDates(HolidayDates);
        leavesAndHolidays.setLeaveDates(totalLeavesData.getLeaveDates());
        leavesAndHolidays.setTotalLeavesHours(totalLeavesData.getTotalHours());
        leavesAndHolidays.setTotalLeavesDays(totalLeavesData.getTotalDays());
        leavesAndHolidays.setTotalWorkingDays(totalDaysInMonth-totalHolidays);

         // Project Summaries

        
        Map<String,Object> ProjectSummaries =
       timesheetFinanceReportService.buildProjectBreakdownForUser(
        userId,
        month,
        year,
        projectDirectory
    );

        
        String employeeName = Optional.ofNullable(allUsers.get(userId))
        .map(u -> (String) u.get("name"))
        .orElse("Unknown User");

         // ✅ Step 6: Calculate total hours (include auto-generated) — recompute per timesheet then HH.MM-aware sum
        BigDecimal totalHours = com.intranet.service.TimeUtil.sumHours(
                timeSheets.stream()
                        .map(com.intranet.service.TimeUtil::computeTimeSheetHours)
                        .collect(Collectors.toList()));

        // 8️⃣ Build DTO
        return MonthlyUserReportDTO.builder()
                .employeeId(userId)
                .employeeName(employeeName)
                .totalHoursWorked(totalHours)
                .billableHours(totalBillableHours)
                .nonBillableHours(totalNonBillableHours)
                .autogeneratedHours(autoGeneratedHours)
                .activeProjectsCount(activeProjectsCount)
                .leavesAndHolidays(leavesAndHolidays)
                .weeklySummaryHistory(getWeeklySummaryHistory(userId, month, year))
                .ProjectSummaries(ProjectSummaries)
                
                .dayWiseSummary(dayWiseSummary)
                
                .build();
    }
    public List<WeekSummaryDTO> getWeeklySummaryHistory(Long userId, int month, int year) {
    LocalDate startOfMonth = LocalDate.of(year, month, 1);
    LocalDate endOfMonth = startOfMonth.withDayOfMonth(startOfMonth.lengthOfMonth());

    // Call the existing WeeklySummaryService method
    WeeklySummaryDTO weeklySummaryDTO = weeklySummaryService
            .getUserWeeklyTimeSheetHistoryRange(userId, startOfMonth, endOfMonth);

    // Returns list of weeks with timesheets
    return weeklySummaryDTO.getWeeklySummary();
    }

    public UserLeaveBreakdown calculateLeaveDetailsForUserReport(
                Long userId, int month, int year, String authHeader) {

        
        // Fetch all leaves for the month using LMS cache
        List<LeaveDTO> leaves = leaveDirectoryService.fetchLeavesUserIdUserReport(userId,year, month, authHeader);

        BigDecimal totalLeaveHours = BigDecimal.ZERO;
        int totalLeaveDays = 0;
        List<LocalDate> leaveDates = new ArrayList<>();

        LocalDate monthStart = LocalDate.of(year, month, 1);
        LocalDate monthEnd = monthStart.withDayOfMonth(monthStart.lengthOfMonth());

        for (LeaveDTO leave : leaves) {

                // Skip different user
                if (!leave.getEmployeeId().equals(userId)) {
                continue;
                }

                // Skip non-approved leaves
                if (!"APPROVED".equalsIgnoreCase(leave.getStatus())) {
                continue;
                }

                LocalDate start = leave.getStartDate();
                LocalDate end = leave.getEndDate();

                // Clamp to month
                LocalDate effectiveStart = start.isBefore(monthStart) ? monthStart : start;
                LocalDate effectiveEnd = end.isAfter(monthEnd) ? monthEnd : end;

                // Iterate dates
                LocalDate date = effectiveStart;
                while (!date.isAfter(effectiveEnd)) {

                switch (date.getDayOfWeek()) {
                        case SATURDAY:
                        case SUNDAY:
                        break; // skip weekends

                        default:
                        totalLeaveHours = totalLeaveHours.add(BigDecimal.valueOf(leaveHours));
                        totalLeaveDays++;
                        leaveDates.add(date);
                }

                date = date.plusDays(1);
                }
        }

        // Build response object
        UserLeaveBreakdown breakdown = new UserLeaveBreakdown();
        breakdown.totalHours = totalLeaveHours;
        breakdown.totalDays = totalLeaveDays;
        breakdown.leaveDates = leaveDates;

        return breakdown;
        }

}
