package com.intranet.service.ManagerEmailReport;

import com.intranet.dto.external.ManagerWeeklySummaryDTO;
import com.intranet.dto.WeekSummaryDTO;
import com.intranet.dto.TimeSheetSummaryDTO;
import com.intranet.dto.TimeSheetEntrySummaryDTO;

import java.util.*;

public class ManagerReportDtoAdapter {

    public static Map<String, Object> adapt(Map<String, Object> rawReport) {

        Map<String, Object> finalMap = new LinkedHashMap<>(rawReport);

        Object userEntries = rawReport.get("userEntriesSummary");

        if (userEntries instanceof List<?> list && !list.isEmpty()
                && list.get(0) instanceof ManagerWeeklySummaryDTO) {

            List<Map<String, Object>> converted = new ArrayList<>();

            for (Object obj : list) {
                converted.add(convertManagerWeekly((ManagerWeeklySummaryDTO) obj));
            }

            finalMap.put("userEntriesSummary", converted);
        }

        return finalMap;
    }

    private static Map<String, Object> convertManagerWeekly(ManagerWeeklySummaryDTO dto) {

        Map<String, Object> m = new LinkedHashMap<>();
        m.put("userId", dto.getUserId());
        m.put("userName", dto.getUserName());
        m.put("billableHours", dto.getBillableHours());
        m.put("nonBillableHours", dto.getNonBillableHours());
        m.put("totalHours", dto.getTotalHours());
        m.put("autogeneratedHours", dto.getAutogeneratedHours());

        List<Map<String, Object>> weekList = new ArrayList<>();
        if (dto.getWeeklySummary() != null) {
            for (WeekSummaryDTO w : dto.getWeeklySummary()) {
                weekList.add(convertWeek(w));
            }
        }
        m.put("weeklySummary", weekList);

        return m;
    }

    private static Map<String, Object> convertWeek(WeekSummaryDTO w) {

        Map<String, Object> m = new LinkedHashMap<>();
        m.put("weekId", w.getWeekId());
        m.put("startDate", w.getStartDate());
        m.put("endDate", w.getEndDate());
        m.put("totalHours", w.getTotalHours());
        m.put("weeklyStatus", w.getWeeklyStatus());

        List<Map<String, Object>> tsList = new ArrayList<>();
        if (w.getTimesheets() != null) {
            for (TimeSheetSummaryDTO ts : w.getTimesheets()) {
                tsList.add(convertTimesheet(ts));
            }
        }
        m.put("timesheets", tsList);
        return m;
    }


    private static Map<String, Object> convertTimesheet(TimeSheetSummaryDTO ts) {

        Map<String, Object> m = new LinkedHashMap<>();
        m.put("timesheetId", ts.getTimesheetId());
        m.put("workDate", ts.getWorkDate());
        m.put("hoursWorked", ts.getHoursWorked());
        m.put("status", ts.getStatus());
        m.put("isHolidayTimesheet", ts.getIsHolidayTimesheet());
        m.put("defaultHolidayTimesheet", ts.getDefaultHolidayTimesheet());

        List<Map<String, Object>> entryList = new ArrayList<>();
        if (ts.getEntries() != null) {
            for (TimeSheetEntrySummaryDTO e : ts.getEntries()) {
                entryList.add(convertEntry(e));
            }
        }
        m.put("entries", entryList);

        return m;
    }

    private static Map<String, Object> convertEntry(TimeSheetEntrySummaryDTO e) {

        Map<String, Object> m = new LinkedHashMap<>();
        m.put("timesheetEntryid", e.getTimesheetEntryid());
        m.put("projectId", e.getProjectId());
        m.put("taskId", e.getTaskId());
        m.put("description", e.getDescription());
        m.put("workLocation", e.getWorkLocation());
        m.put("fromTime", e.getFromTime());
        m.put("toTime", e.getToTime());
        m.put("hoursWorked", e.getHoursWorked());
        m.put("otherDescription", e.getOtherDescription());
        m.put("isBillable", e.getIsBillable());

        return m;
    }

}
