package com.intranet.service.ManagerEmailReport;

import java.lang.reflect.Method;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;

/**
 * Safe XHTML template builder for Manager Monthly Report.
 * - Escapes all dynamic text.
 * - Produces well-formed XHTML.
 * - Tolerant to Map-based or DTO-based report structures (uses reflection fallback).
 */
@Service
public class ManagerPdfTemplateBuilder {
    private String monthName(int monthNumber) {
    String name = java.time.Month.of(monthNumber).name(); // "NOVEMBER"
    return name.substring(0,1) + name.substring(1).toLowerCase(); // "November"
    }

    public String buildManagerMonthlyReportHtml(Map<String, Object> report, String managerName) {

        if (report == null) report = java.util.Collections.emptyMap();

        // Safe extraction helpers
        String monthStr = safeToString(get(report, "month"));
        String yearStr  = safeToString(get(report, "year"));

        Object totalHoursObj = get(report, "totalHours");
        Object billableHoursObj = get(report, "billableHours");
        Object nonBillableHoursObj = get(report, "nonBillableHours");
        Object autoGeneratedHoursObj = get(report, "autoGeneratedHours");
        Object billablePercentageObj = get(report, "billablePercentage");
        Object pendingObj = get(report, "pending");

        Map<String, Object> dateRange = safeCastMap(get(report, "dateRange"));
        String startDateStr = "";
        String endDateStr = "";
        if (dateRange != null) {
            Object s = dateRange.get("startDate");
            Object e = dateRange.get("endDate");
            startDateStr = safeToString(s);
            endDateStr   = safeToString(e);
        }

        String expectedHoursStr = safeToString(get(report, "expectedHours"));

        Map<String, Object> weeklySummary = safeCastMap(get(report, "weeklySummary"));
        List<?> pendingUsers = safeCastList(get(report, "pendingUsers"));
        List<?> projectBreakdown = safeCastList(get(report, "projectBreakdown"));
        Map<String, Object> billableContribution = safeCastMap(get(report, "billableContribution"));
        Map<String, Object> nonBillableContribution = safeCastMap(get(report, "nonBillableContribution"));
        Map<String, Object> autoContribution = safeCastMap(get(report, "autoGeneratedContribution"));

        List<?> underutilized = safeCastList(get(report, "underutilizedInsight") == null ? null :
                safeCastMap(get(report, "underutilizedInsight")).get("underutilized"));
        List<?> overworked = safeCastList(get(report, "overworkedInsight") == null ? null :
                safeCastMap(get(report, "overworkedInsight")).get("overworked"));
        List<?> multiProject = safeCastList(get(report, "multiProjectWorkersInsight") == null ? null :
                safeCastMap(get(report, "multiProjectWorkersInsight")).get("multiProjectWorkers"));

        List<?> userEntriesSummary = safeCastList(get(report, "userEntriesSummary"));

        StringBuilder html = new StringBuilder(32_000);

        // XML declaration is optional for openhtmltopdf, but DO NOT prepend stray characters
        html.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
        html.append("<!DOCTYPE html>");
        html.append("<html xmlns=\"http://www.w3.org/1999/xhtml\">");
        html.append("<head>");
        html.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>");
        html.append("<style type=\"text/css\">");
        html.append("body { font-family: Arial, sans-serif; margin: 20px; color: #222; }");
        html.append("h1 { color: #1f4e79; font-size: 20px; }");
        html.append("h2 { color: #2c3e50; font-size: 16px; margin-top: 18px; }");
        html.append("table { width: 100%; border-collapse: collapse; margin-top: 10px; }");
        html.append("th, td { border: 1px solid #ddd; padding: 6px; font-size: 12px; }");
        html.append("th { background: #f5f7fa; text-align: left; }");
        html.append(".summary { padding: 12px; border-left: 6px solid #007bff; background: #f0f7ff; }");
        html.append(".muted { color: #666; font-size: 12px; }");
        html.append(".small { font-size: 11px; }");
        html.append(".section { margin-top: 18px; page-break-inside: avoid;}");
        html.append(".no-break { page-break-inside: avoid; }");
        html.append(".badge { display:inline-block; padding:4px 8px; background:#e9f5ff; border-radius:4px; margin-right:6px; }");
        html.append("</style>");
        html.append("</head>");
        html.append("<body>");

        // Header
        html.append("<h1>Manager Monthly Report</h1>");
        String period = monthName(Integer.parseInt(monthStr)) + " " + yearStr;

        html.append("<p class=\"muted\"><strong>")
            .append(esc(period))
            .append("</strong></p>");

        html.append("<p class=\"muted\">Manager: <strong>").append(esc(managerName)).append("</strong></p>");

        // Summary box
        html.append("<div class=\"summary no-break\">");
        html.append("<h2>Summary</h2>");
        html.append("<table><tr><th>Metric</th><th>Value</th></tr>");

        appendRowSafe(html, "Month / Year", esc(monthStr + " / " + yearStr));
        appendRowSafe(html, "Total Hours", esc(safeToString(totalHoursObj)));
        appendRowSafe(html, "Billable Hours", esc(safeToString(billableHoursObj)));
        appendRowSafe(html, "Non-Billable Hours", esc(safeToString(nonBillableHoursObj)));
        appendRowSafe(html, "Auto-Generated Hours", esc(safeToString(autoGeneratedHoursObj)));
        appendRowSafe(html, "Billable %", esc(safeToString(billablePercentageObj)));
        appendRowSafe(html, "Pending Timesheets", esc(safeToString(pendingObj)));

        html.append("</table>");
        html.append("</div>");

        // ---------------------------
        // Missing Timesheets
        // ---------------------------
        html.append("<div class=\"section no-break\">");
        html.append("<h2>Missing Timesheets (Last 15 Days)</h2>");

        List<?> missingList = safeCastList(get(report, "missingTimesheets"));

        if (missingList == null || missingList.isEmpty()) {
            html.append("<p class=\"muted\">All users submitted their timesheets ✔</p>");
        } else {

            html.append("<table>");
            html.append("<tr><th>User</th><th>User ID</th><th>Email</th></tr>");

            for (Object m : missingList) {
                String name = safeGetAsString(m, "fullName");
                String uid  = safeGetAsString(m, "userId");
                String mail = safeGetAsString(m, "email");

                html.append("<tr>")
                    .append("<td>").append(esc(name)).append("</td>")
                    .append("<td>").append(esc(uid)).append("</td>")
                    .append("<td>").append(esc(mail)).append("</td>")
                    .append("</tr>");
            }

            html.append("</table>");
        }

        html.append("</div>");


        // Weekly Summary
        html.append("<div class=\"section no-break\">");
        html.append("<h2>Weekly Summary (Day-wise)</h2>");
        html.append("<table><tr><th>Day</th><th>Total Hours</th></tr>");
        if (weeklySummary != null && !weeklySummary.isEmpty()) {
            for (Map.Entry<String, Object> e : weeklySummary.entrySet()) {
                html.append("<tr><td>").append(esc(e.getKey())).append("</td><td>")
                    .append(esc(safeToString(e.getValue()))).append("</td></tr>");
            }
        } else {
            html.append("<tr><td colspan=\"2\" class=\"muted\">No weekly summary available</td></tr>");
        }
        html.append("</table>");
        html.append("</div>");

        // Pending Users
        html.append("<div class=\"section no-break\">");
        html.append("<h2>Pending Users</h2>");
        if (pendingUsers == null || pendingUsers.isEmpty()) {
            html.append("<p class=\"muted\">No pending users — all timesheets submitted.</p>");
        } else {
            html.append("<table><tr><th>User</th><th>User ID</th><th>Pending Weeks</th></tr>");
            for (Object o : pendingUsers) {
                String userName = safeGetAsString(o, "userName");
                String userId   = safeGetAsString(o, "userId");
                String pendingWeeks = safeGetAsString(o, "pendingWeeks");
                html.append("<tr><td>").append(esc(userName)).append("</td><td>")
                    .append(esc(userId)).append("</td><td>").append(esc(pendingWeeks)).append("</td></tr>");
            }
            html.append("</table>");
        }
        html.append("</div>");



        // Project Breakdown
        html.append("<div class=\"section no-break\">");
        html.append("<h2>Project Breakdown</h2>");
        if (projectBreakdown == null || projectBreakdown.isEmpty()) {
            html.append("<p class=\"muted\">No projects found.</p>");
        } else {
            html.append("<table>");
            html.append("<tr><th>Project</th><th>Total Hours</th><th>Billable</th><th>Non-Billable</th><th>Billable %</th></tr>");
            for (Object p : projectBreakdown) {
                String projName = safeGetAsString(p, "projectName");
                String totalH = safeGetAsString(p, "totalHours");
                String billH  = safeGetAsString(p, "billableHours");
                String nonH   = safeGetAsString(p, "nonBillableHours");
                String billPct= safeGetAsString(p, "billablePercentage");
                html.append("<tr><td>").append(esc(projName)).append("</td><td>").append(esc(totalH))
                    .append("</td><td>").append(esc(billH)).append("</td><td>").append(esc(nonH))
                    .append("</td><td>").append(esc(billPct)).append("</td></tr>");
            }
            html.append("</table>");
        }
        html.append("</div>");

        // ----------------------------------
        // Project Breakdown (Grouped)
        // ----------------------------------
        html.append("<div class=\"section no-break\">");
        html.append("<h2>Project Breakdown (With Member Contributions)</h2>");

        if (projectBreakdown == null || projectBreakdown.isEmpty()) {

            html.append("<p class=\"muted\">No project data found.</p>");

        } else {

            for (Object pObj : projectBreakdown) {

                String pName = safeGetAsString(pObj, "projectName");
                String totalH = safeGetAsString(pObj, "totalHours");
                String billH  = safeGetAsString(pObj, "billableHours");
                String nonH   = safeGetAsString(pObj, "nonBillableHours");
                String billPct= safeGetAsString(pObj, "billablePercentage");

                // Project Header
                html.append("<h3 style=\"margin-bottom:4px;\">")
                        .append(esc(pName))
                        .append("</h3>");

                // Primary project summary table
                html.append("<table class=\"no-break\">");
                html.append("<tr><th>Total Hours</th><td>").append(esc(totalH)).append("</td></tr>");
                html.append("<tr><th>Billable Hours</th><td>").append(esc(billH)).append("</td></tr>");
                html.append("<tr><th>Non-Billable Hours</th><td>").append(esc(nonH)).append("</td></tr>");
                html.append("<tr><th>Billable %</th><td>").append(esc(billPct)).append("</td></tr>");
                html.append("</table>");

                // Members Section
                List<?> members = safeCastList(safeGet(pObj, "membersContribution"));

                html.append("<p style=\"margin-top:10px;\"><strong>Member Contributions</strong></p>");

                if (members == null || members.isEmpty()) {

                    html.append("<p class=\"muted\">No members assigned</p>");

                } else {

                    html.append("<table class=\"no-break\">");
                    html.append("<tr>")
                            .append("<th>Member</th>")
                            .append("<th>User ID</th>")
                            .append("<th>Hours</th>")
                            .append("<th>Contribution %</th>")
                            .append("</tr>");

                    for (Object m : members) {
                        html.append("<tr>")
                                .append("<td>").append(esc(safeGetAsString(m, "userName"))).append("</td>")
                                .append("<td>").append(esc(safeGetAsString(m, "userId"))).append("</td>")
                                .append("<td>").append(esc(safeGetAsString(m, "totalHours"))).append("</td>")
                                .append("<td>").append(esc(safeGetAsString(m, "contribution"))).append("</td>")
                                .append("</tr>");
                    }

                    html.append("</table>");
                }

                html.append("<hr/>");
            }
        }

        html.append("</div>");


        // User Contribution: Billable, Non-billable, Auto-generated
        html.append("<div class=\"section no-break\">");
        html.append("<h2>User Contributions</h2>");

        appendContributionBlock(html, "Billable Contribution", billableContribution, "billableHours");
        appendContributionBlock(html, "Non-Billable Contribution", nonBillableContribution, "nonBillableHours");
        appendContributionBlock(html, "Auto-Generated Contribution", autoContribution, "autoHours");

        html.append("</div>");

        // Insights
        html.append("<div class=\"section no-break\">");
        html.append("<h2>Insights</h2>");

        appendInsightTable(html, "Underutilized Employees", underutilized, "totalHours",expectedHoursStr);
        appendInsightTable(html, "Overworked Employees", overworked, "totalHours",expectedHoursStr);
        appendInsightTableMulti(html, "Multi-Project Workers", multiProject, "projectCount");

        html.append("</div>");

        // Per-user weekly details
        html.append("<div class=\"section\">");
        html.append("<h2>User Weekly Timesheet Summaries</h2>");
        if (userEntriesSummary == null || userEntriesSummary.isEmpty()) {
            html.append("<p class=\"muted\">No user entries available.</p>");
        } else {
            for (Object userObj : userEntriesSummary) {

                String uname = safeGetAsString(userObj, "userName");
                String uid   = safeGetAsString(userObj, "userId");
                String totalHoursUser = safeGetAsString(userObj, "totalHours");

                html.append("<div class=\"no-break\">");
                html.append("<h3>").append(esc(uname)).append(" (").append(esc(uid)).append(")</h3>");
                html.append("<p class=\"small\"><strong>Total Hours:</strong> ").append(esc(totalHoursUser)).append("</p>");

                List<?> weeks = safeCastList(safeGet(userObj, "weeklySummary"));
                if (weeks != null && !weeks.isEmpty()) {
                    for (Object weekObj : weeks) {
                        String weekId = safeGetAsString(weekObj, "weekId");
                        String wStart = safeGetAsString(weekObj, "startDate");
                        String wEnd   = safeGetAsString(weekObj, "endDate");
                        String wTotal = safeGetAsString(weekObj, "totalHours");
                        String wStatus= safeGetAsString(weekObj, "weeklyStatus");

                        html.append("<div style=\"background:#f8f9fa;padding:8px;margin-top:8px;border-radius:4px;\">");
                        html.append("<strong>Week ").append(esc(weekId)).append(":</strong> ")
                            .append(esc(wStart)).append(" → ").append(esc(wEnd))
                            .append(" &#160; <span class=\"small\">(").append(esc(wStatus)).append(")</span>");
                        html.append("<div class=\"small\">Total: ").append(esc(wTotal)).append("</div>");
                        html.append("</div>");

                        // timesheets table
                        List<?> tsList = safeCastList(safeGet(weekObj, "timesheets"));
                        html.append("<table>");
                        html.append("<tr><th>Date</th><th>Project</th><th>Task</th><th>Hours</th><th>Billable</th><th>Description</th></tr>");
                        if (tsList != null && !tsList.isEmpty()) {
                            for (Object ts : tsList) {
                                String workDate = safeGetAsString(ts, "workDate");
                                List<?> entries = safeCastList(safeGet(ts, "entries"));
                                if (entries == null || entries.isEmpty()) {
                                    // row for autogenerated / holiday empty entries
                                    String hw = safeGetAsString(ts, "hoursWorked");
                                    html.append("<tr><td>").append(esc(workDate)).append("</td>")
                                        .append("<td colspan=\"5\" class=\"muted\">Auto/holiday/default timesheet (hours=").append(esc(hw)).append(")</td></tr>");
                                } else {
                                    for (Object ent : entries) {
                                        String pId = safeGetAsString(ent, "projectId");
                                        String tId = safeGetAsString(ent, "taskId");
                                        String hrs = safeGetAsString(ent, "hoursWorked");
                                        String bill = safeGetAsString(ent, "isBillable");
                                        String desc = safeGetAsString(ent, "description");
                                        html.append("<tr><td>").append(esc(workDate)).append("</td><td>")
                                            .append(esc(pId)).append("</td><td>").append(esc(tId)).append("</td><td>")
                                            .append(esc(hrs)).append("</td><td>").append(esc(bill)).append("</td><td>")
                                            .append(esc(desc)).append("</td></tr>");
                                    }
                                }
                            }
                        } else {
                            html.append("<tr><td colspan=\"6\" class=\"muted\">No timesheets for this week</td></tr>");
                        }
                        html.append("</table>");
                    }
                } else {
                    html.append("<p class=\"muted\">No weekly summaries for this user.</p>");
                }
                html.append("<hr/>");
                html.append("</div>");
            }
        }
        html.append("</div>");


        html.append("""
            <div style="margin-top:25px; padding:15px; background:#f7faff; border-left:6px solid #4a90e2; border-radius:6px;">
                <h2 style="margin-top:0;">Report Notes</h2>
                <ul style="font-size:12px; line-height:1.6; padding-left:18px;">

                    <li>
                        <strong>Billable Hours:</strong> Total hours spent by team members on tasks classified as billable across all assigned projects.
                    </li>

                    <li>
                        <strong>Non-Billable Hours:</strong> Total hours logged on tasks marked as non-billable across all projects.
                    </li>

                    <li>
                        <strong>Total Hours:</strong> Sum of Billable Hours and Non-Billable Hours.
                    </li>

                    <li>
                        <strong>Billable Utilization (&#37;):</strong> (Billable Hours &#247; Total Hours) &#215; 100.
                    </li>

                    <li>
                        <strong>Minimum Monthly Hours Requirement:</strong> 176 hours per employee (22 working days &#215; 8 hours/day).
                    </li>

                    <li>
                        <strong>Active Projects:</strong> Total number of projects that had at least one timesheet entry during the selected month.
                    </li>

                    <li>
                        <strong>Project Allocation Hours:</strong> Total hours contributed to each project by all associated team members.
                    </li>

                    <li>
                        <strong>Daily Contribution:</strong> Daily distribution of the total hours logged by the team for the selected month.
                    </li>

                    <li>
                        <strong>Billable vs Non-Billable (Overall):</strong> Comparison showing how the team’s hours were divided between billable and non-billable work.
                    </li>

                    <li>
                        <strong>Underutilized Employees:</strong> Employees whose total logged hours fall below the minimum monthly requirement.
                    </li>

                    <li>
                        <strong>Overworked Employees:</strong> Employees whose logged hours exceed acceptable capacity (for example, over 176 hours in one month).
                    </li>

                    <li>
                        <strong>Pending Timesheets:</strong> Number of team members who have not submitted timesheets within the last 15 days.
                    </li>

                    <li>
                        <strong>Billing Data Accuracy:</strong> All calculations are based only on submitted timesheets; missing entries may reduce accuracy.
                    </li>

                    <li>
                        <strong>Average Billable Percentage:</strong> The average of billable percentage values for all projects during the selected month.
                    </li>

                </ul>
            </div>
            """);


        // Footer
        html.append("<p class=\"muted\" style=\"text-align:center;margin-top:20px;\">Report generated by Timesheet Management System on ")
            .append(esc(LocalDateTime.now().toString())).append("</p>");

        html.append("</body></html>");

        // final string
        return html.toString();
    }

    // ================= Helper: safe access and conversion =================

    @SuppressWarnings("unchecked")
    private Map<String, Object> safeCastMap(Object o) {
        if (o instanceof Map) return (Map<String,Object>) o;
        return null;
    }

    @SuppressWarnings("unchecked")
    private List<?> safeCastList(Object o) {
        if (o instanceof List) return (List<?>) o;
        return null;
    }

    private Object get(Map<String, Object> m, String key) {
        if (m == null) return null;
        return m.get(key);
    }

    private Object safeGet(Object obj, String prop) {
        if (obj == null) return null;
        if (obj instanceof Map) return ((Map) obj).get(prop);
        // try reflection: getXxx() or isXxx()
        try {
            String camel = Character.toUpperCase(prop.charAt(0)) + prop.substring(1);
            Method m = null;
            try { m = obj.getClass().getMethod("get" + camel); } catch (Exception ex) {}
            if (m == null) {
                try { m = obj.getClass().getMethod("is" + camel); } catch (Exception ex) {}
            }
            if (m != null) return m.invoke(obj);
        } catch (Exception ignore) {}
        return null;
    }

    private String safeGetAsString(Object obj, String prop) {
        Object v = safeGet(obj, prop);
        return safeToString(v);
    }

    private String safeToString(Object o) {
        if (o == null) return "";
        // If LocalDate / LocalDateTime, use toString (already ok)
        return o.toString();
    }

    // Escape for XML/XHTML
    private String esc(String s) {
        if (s == null) return "";
        StringBuilder r = new StringBuilder(s.length() + 10);
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            switch (c) {
                case '&': r.append("&amp;"); break;
                case '<': r.append("&lt;"); break;
                case '>': r.append("&gt;"); break;
                case '"': r.append("&quot;"); break;
                case '\'': r.append("&#39;"); break;
                default: r.append(c);
            }
        }
        return r.toString();
    }

    // small utility to append a table row safely (avoids repeated format)
   private void appendRowSafe(StringBuilder sb, String label, String value) {
    sb.append("<tr><th>")
      .append(esc(label))
      .append("</th><td>")
      .append(esc(value))
      .append("</td></tr>");
    }


    // helper used above (not visible outside)
    private void appendContributionBlock(StringBuilder html, String title, Map<String, Object> contribution, String hourField) {
        html.append("<h3>").append(esc(title)).append("</h3>");
        if (contribution == null) {
            html.append("<p class=\"muted\">No data</p>");
            return;
        }
        List<?> members = safeCastList(contribution.get("members"));
        if (members == null || members.isEmpty()) {
            html.append("<p class=\"muted\">No members</p>");
            return;
        }
        html.append("<table><tr><th>User</th><th>User ID</th><th>Hours</th><th>Contribution %</th></tr>");
        for (Object m : members) {
            String name = safeGetAsString(m, "userName");
            String id   = safeGetAsString(m, "userId");
            String hrs  = safeGetAsString(m, hourField);
            String contrib = safeGetAsString(m, "contribution");
            html.append("<tr><td>").append(esc(name)).append("</td><td>").append(esc(id)).append("</td><td>")
                .append(esc(hrs)).append("</td><td>").append(esc(contrib)).append("</td></tr>");
        }
        html.append("</table>");
    }

    private void appendInsightTable(StringBuilder html, String title, List<?> list, String metricField,String expectedHours) {
         html.append("<h3>")
            .append(esc(title));

        if (expectedHours != null && !expectedHours.isBlank()) {
            html.append(" <span class=\"small\">(Expected Hours: ")
                .append(esc(expectedHours))
                .append(")</span>");
        }

        html.append("</h3>");
        if (list == null || list.isEmpty()) {
            html.append("<p class=\"muted\">None</p>");
            return;
        }
        html.append("<table><tr><th>User</th><th>User ID</th><th>").append(esc(metricField)).append("</th></tr>");
        for (Object item : list) {
            String name = safeGetAsString(item, "userName");
            String id   = safeGetAsString(item, "userId");
            String metric = safeGetAsString(item, metricField);
            html.append("<tr><td>").append(esc(name)).append("</td><td>").append(esc(id)).append("</td><td>")
                .append(esc(metric)).append("</td></tr>");
        }
        html.append("</table>");
    }
    private void appendInsightTableMulti(StringBuilder html, String title, List<?> list, String metricField) {
        html.append("<h3>").append(esc(title)).append("</h3>");
        if (list == null || list.isEmpty()) {
            html.append("<p class=\"muted\">None</p>");
            return;
        }
        html.append("<table><tr><th>User</th><th>User ID</th><th>").append(esc(metricField)).append("</th></tr>");
        for (Object item : list) {
            String name = safeGetAsString(item, "userName");
            String id   = safeGetAsString(item, "userId");
            String metric = safeGetAsString(item, metricField);
            html.append("<tr><td>").append(esc(name)).append("</td><td>").append(esc(id)).append("</td><td>")
                .append(esc(metric)).append("</td></tr>");
        }
        html.append("</table>");
    }
}
