name: Deploy TimeSheetManagement to EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup JDK 17
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 3️⃣ Build the JAR
      - name: Build JAR
        run: mvn clean package -DskipTests

      # 4️⃣ Verify local JAR exists
      - name: Verify local JAR
        run: |
          ls -lh target/ | grep TimeSheetManagement.jar
          file target/TimeSheetManagement.jar

      # 5️⃣ Remove old JAR on EC2
      - name: Remove old JAR on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: rm -f ${{ secrets.EC2_PATH }}/TimeSheetManagement.jar

      # 6️⃣ Upload JAR to EC2
      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/TimeSheetManagement.jar"            # exact file
          target: "${{ secrets.EC2_PATH }}/TimeSheetManagement.jar" # destination file
          rm: false
          strip_components: 0

      # 7️⃣ Verify JAR on EC2
      - name: Verify JAR on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            ls -lh ${{ secrets.EC2_PATH }}/TimeSheetManagement.jar
            file ${{ secrets.EC2_PATH }}/TimeSheetManagement.jar

      # 8️⃣ Restart systemd service
      - name: Restart timesheet.service
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart timesheet.service
            sleep 5
            sudo systemctl status timesheet.service --no-pager

      # 9️⃣ Optional: Health check (Spring Boot actuator)
      - name: Health Check
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            curl -f http://localhost:5000/actuator/health || exit 1
