name: Deploy TimeSheetManagement to EC2

# Trigger on push to main or manual run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 3️⃣ Build the JAR
      - name: Build JAR
        run: mvn clean package -DskipTests

      # 4️⃣ Verify JAR exists locally
      - name: Verify Local JAR
        run: |
          ls -lh target/ | grep TimeSheetManagement.jar
          file target/TimeSheetManagement.jar

      # 5️⃣ Upload JAR to EC2
      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/TimeSheetManagement.jar"
          target: "${{ secrets.EC2_PATH }}/"
          rm: false  # don’t delete remote folder

      # 6️⃣ Verify JAR on EC2
      - name: Verify JAR on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            ls -lh ${{ secrets.EC2_PATH }}/TimeSheetManagement.jar
            file ${{ secrets.EC2_PATH }}/TimeSheetManagement.jar

      # 7️⃣ Restart systemd service
      - name: Restart timesheet.service
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart timesheet.service
            sleep 5
            sudo systemctl status timesheet.service --no-pager

      # 8️⃣ Optional: Health check
      - name: Health Check
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            curl -f http://localhost:5000/actuator/health || exit 1
